### ISSUE TITLE
docs: in the YAML schema, fix the link to `product_quality.yaml`

### ISSUE THREAD

**Issue by jforget** [openfoodfacts/openfoodfacts-server#11275]
The `product.yaml` file uses the following components, among others:

```
allOf:
  - $ref: "../api.yml#/components/schemas/Product-Data-Quality"
  - $ref: "../api.yml#/components/schemas/Product-Knowledge-Panels"
```

The `api.yml` file defines the following components (among others):

```
components:
  schemas:
    "Product-Quality":
      $ref: ./schemas/product_quality.yaml
    "Product-Data-Quality":
      $ref: ./schemas/product_knowledge_panels.yaml
    "Product-Knowledge-Panels":
      $ref: ./schemas/product_knowledge_panels.yaml
```

It seems there was a copy-paste-fail error.

There are two possible fixes:

(1) `product.yaml`  should refer to `Product-Quality` instead of `Product-Data-Quality`
and in `api.yml` the component `Product-Data-Quality` should be removed

(2) in `api.yml`, the component `Product-Data-Quality` should point to file `product_quality.yaml`
