### ISSUE TITLE
Data quality error: 8 consonants or more

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#11302]
Fields with words containing 7 consonants in a row are possible:
* product name (rare): Hirschschnitzel
* brands: some brands do contain 6 consonants, such as knightsbridge, feldschlosschen
* ingredients: some ingredients' lists seem to contain at least "durchschnittliche" (german word), with 7 consonants

But I was not able to find real words with 8 or more consonants in a row, excepting:
* the product names "Frutchtschnitte" and "Borschtsch" (8 consonants)
* names with Roman numbers. Eg. MDLCCXXXVI contains 9 consonants in a row.

In Mirabelle, I have searched for products containing 8 consonants in a row:
* for the fields `product_name`, `brands_tags`, `ingredients_tags`
* excepting Romand numbers and "Frutchtschnitte" and "Borschtsch"
The result is [410 products as of today](https://mirabelle.openfoodfacts.org/products?sql=--+most+scaned+products+with+data+quality+error%0D%0Aselect+product_name%2C+brands_tags%2C+countries_tags%2C+unique_scans_n%2C+url%2C+data_quality_errors_tags%2C+image_nutrition_url%0D%0Afrom+%5Ball%5D+where%0D%0A+%28lower%28product_name%29+REGEXP+%22%5Bb-df-hj-np-tv-xz%5D%7B8%2C%7D%22+and+lower%28product_name%29+NOT+REGEXP+%22mdcc%3Fc%3Fl%3Fxxx%3Fv%3F%7Cborschtsch%7Cfrutchtschnitt%22%29%0D%0A++or+%28brands_tags+REGEXP+%22%5Bb-df-hj-np-tv-xz%5D%7B8%2C%7D%22+and+brands_tags+NOT+REGEXP+%22mdcc%3Fc%3Fl%3Fxxx%3Fv%3F%7Cborschtsch%7Cfrutchtschnitt%22%29%0D%0A++or+%28ingredients_tags+REGEXP+%22%5Bb-df-hj-np-tv-xz%5D%7B8%2C%7D%22+and+ingredients_tags+NOT+REGEXP+%22mdccc%3Fl%3Fxxx%3Fv%3F%7Cborschtsch%7Cfrutchtschnitt%22%29%0D%0Aorder+by+unique_scans_n+desc%0D%0Alimit+500) (2025-01-27).

Many of these products are vandalism. Many others are just bad OCR.

TODO: look at other fields.

**Comment by CharlesNepote** [comment]
@benbenben2 : do you think you can work on this? May I assign you?

It seems not very important, but it allows to discover junk data such as in:
* https://world.openfoodfacts.org/product/8713576007749/terrasana-vliespinda-s-geroosterd-en-gezouten-biologisch?rev=10 (ingredients)
* https://world.openfoodfacts.org/product/8410376031898/twins-gullon?rev=28 (ingredients)

**Comment by benbenben2** [comment]
Yes, sure @CharlesNepote 

For ingredients, there is already facet for 5 consonants. But it ignores German
```
# Dutch and other languages can have 4 consecutive consonants
if ($display_lc !~ /de|hr|nl|pl/) {
	if ($product_ref->{$ingredients_text_lc} =~ /[bcdfghjklmnpqrstvwxz]{5}/is) {

		push @{$product_ref->{data_quality_warnings_tags}},
			"en:ingredients-" . $display_lc . "-5-consonants";
	}
}
```

Two options:
1) something like
```
# Dutch and other languages can have 4 consecutive consonants
if ($display_lc !~ /de|hr|nl|pl/) {
	if ($product_ref->{$ingredients_text_lc} =~ /[bcdfghjklmnpqrstvwxz]{5}/is) {

		push @{$product_ref->{data_quality_warnings_tags}},
			"en:ingredients-" . $display_lc . "-5-consonants";
	}
} else {
	if ($product_ref->{$ingredients_text_lc} =~ /[bcdfghjklmnpqrstvwxz]{8}/is and <ignore Frutchtschnitte" and Borschtsch> ) {

		push @{$product_ref->{data_quality_warnings_tags}},
			"en:ingredients-" . $display_lc . "-8-consonants";
	}
}
```

2) something like
```
# Dutch and other languages can have 4 consecutive consonants
list_of_accepted_words_with_many_consecutive_consonants = ["Frutchtschnitte", "Borschtsch"]

if ($product_ref->{$ingredients_text_lc} =~ /[bcdfghjklmnpqrstvwxz]{5}/is and not list_of_accepted_words_with_many_consecutive_consonants) {
	push @{$product_ref->{data_quality_warnings_tags}},
		"en:ingredients-" . $display_lc . "-5-consonants";
}
```
With second option it needs to create a list of accepted words. In the code of product opener. I would ignore languages for now and put them all in the same list for now. But we could have something more complex like for the stopwords in ingredients (per lang).


@stephane if you have recommendations before I start implementing that, feel free to share.


For product name and brand name,
Suggestion: 
if > 8, push facet

**Comment by CharlesNepote** [comment]
When I see your implementation suggestions, I'm asking myself if there could be a way that scale better.

Could we have some sort of conf file or taxonomy like that (in YAML, but it can be [in another format](https://en.wikipedia.org/wiki/Configuration_file#Comparison)):
```yaml
---
name: -5-consonants
regexp: [bcdfghjklmnpqrstvwxz]{5}
description: Words with 5 consonants or more, except Frutchtschnitte or Borschtsch
fields:
- product_name
- ingredients_text_lc
type: errors
exception_regexp: Frutchtschnitte|Borschtsch
# a comment if necessary

name: -5-voyels
regexp: [aeiou]{5}
fields:
- product_name
- ingredients_text_lc
type: warnings
exception_regexp:

name: -html-entity-codes
regexp: "&(amp|gt|lt)"
fields:
- product_name
- ingredients_text_lc
type: errors
exception_regexp:
```

It would let us add more and more filters, without using Perl. We could previously test all these detections with Mirabelle.
We could easily add exceptions.
