### ISSUE TITLE
Android button size X2

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2205]
![image](https://user-images.githubusercontent.com/1689815/63332497-04f10500-c338-11e9-9ec9-c4da279aec88.png)

**Comment by VaiTon** [comment]
```css
footer .app > a > img {
    width: 100%;
    height: 100%;
}
footer .app a {
    padding: 5px;
}
```

Add this to css
