### ISSUE TITLE
docker-compose slow on off-net

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6164]
### Describe the bug

running docker-compose run or up commands are very slow on preprod for off-net

### To Reproduce

On preprod in /home/off/off-net, run:
```
docker-compose run --rm backend bash
```
it will be really slow. The "creating container" phase is taking much time.

### Expected behavior

This should take less than one second

### Type of device

Other

**Comment by alexgarel** [comment]
From what I see in syslog, creating volume takes time. Excerpt:

```
Dec  8 06:55:49 dockers systemd[1]: run-docker-runtime\x2drunc-moby-b77bd5fe0e22d737197b393b8f86a8fe8388feb613cde4b2a0bfcae303e1d4a3-runc.X6Frsu.mount: Succeeded. 
Dec  8 06:56:18 dockers systemd[1800077]: run-docker-runtime\x2drunc-moby-d2bce4c8aaadb7f4d57bfc069137ea124fbe5dd94b575aff3a49ce1d263be2de-runc.7G2iOF.mount: Succeeded. 
Dec  8 06:56:19 dockers systemd[1800077]: run-docker-runtime\x2drunc-moby-b77bd5fe0e22d737197b393b8f86a8fe8388feb613cde4b2a0bfcae303e1d4a3-runc.R4BO77.mount: Succeeded.
Dec  8 06:57:50 dockers systemd[1800077]: run-docker-runtime\x2drunc-moby-b77bd5fe0e22d737197b393b8f86a8fe8388feb613cde4b2a0bfcae303e1d4a3-runc.v9aSVO.mount: Succeeded.
```

We have around 1 minute for some mounts !

I have done some tests.

Notably:

```
docker run -ti --rm \
-v /home/off/off-web-net/lang:/mnt/podata/lang \
-v po_icons_dist:/opt/product-opener/html/images/icons/dist:ro \
-v po_js_dist:/opt/product-opener/html/js/dist:ro \
-v po_css_dist:/opt/product-opener/html/css/dist:ro \
-v po_node_modules:/opt/product-opener/node_modules:ro \
-v html_data:/opt/product-opener/html/data \
-v users:/mnt/podata/users \
-v products:/mnt/podata/products \
-v product_images:/opt/product-opener/html/images/products \
-v orgs:/mnt/podata/orgs \
-v podata:/mnt/podata \
-v /home/off/off-net/logs/apache2:/var/log/apache2 \
-v /home/off/off-net/logs/apache2:/mnt/podata/logs \
-v /home/off/off-net/logs/apache2:/var/log/httpd \
-v /home/off/off-net/conf/apache.conf:/etc/apache2/sites-enabled/product-opener.conf \
bitnami/minideb:buster bash
```
is really fast !

Also if I comment out : users / products / products_images / orgs volumes, this is fast. (podata does not have problems).

Note: this is not an [entropy issue](https://github.com/docker/compose/issues/6678), /proc/sys/kernel/random/entropy_avail is above 3000 all the time

Conclusion:
1. creation of container is slow because of volumes that are located in /mnt (users / products / products_images / orgs)
2. this is slow only if we run using docker-compose, not when using docker

**Comment by alexgarel** [comment]
@ocervell I think you may be interested in this issue…

**Comment by ocervell** [comment]
@alexgarel yes, probably mounting 4M files takes a bit of time, which also explains why we don't see it in development environment. Maybe it that situation we should favor `exec` over `run` to not re-create the volumes every time ?

**Comment by alexgarel** [comment]
> probably mounting 4M files takes a bit of time

I don't think this is the problem, as written above, if we use `docker run` with same mounts directly, this is instantaneous. So this really seems to be something with docker-compose.

**Comment by alexgarel** [comment]
One test to be done is to add volumes directly using NFS driver. I did that for monitoring.
The fact that we use bind mount on an NFS volume might be a problem.

**Comment by alexgarel** [comment]
Tried to create volumes to test:

```bash
docker volume create --driver local --opt type=nfs --opt o=addr=10.0.0.3,rw  --opt device=:/rpool/off/clones/products po_nfs_products
docker volume create --driver local --opt type=nfs --opt o=addr=10.0.0.3,rw  --opt device=:/rpool/off/clones/users po_nfs_users
docker volume create --driver local --opt type=nfs --opt o=addr=10.0.0.3,rw  --opt device=:/rpool/off/clones/orgs po_nfs_orgs
docker volume create --driver local --opt type=nfs --opt o=addr=10.0.0.3,rw  --opt device=:/rpool/off/clones/images/products po_nfs_product_images
```

with a test.yml which is a copy of docker/prod.yml but setting a specific name for external volumes so that they maps to the above:
```yml
volumes:
  html_data:
    external: true
  users:
    external: true
    name: po_nfs_users
  products:
    external: true
    name: po_nfs_products
  orgs:
    external: true
    name: po_nfs_orgs
  product_images:
    external: true
    name: po_nfs_product_images
  podata:
    external: true
...

and run:

```bash
time COMPOSE_PATH_SEPARATOR=";" COMPOSE_FILE="docker-compose.yml;../test.yml" docker-compose run --rm --entrypoint bash backend -c "echo hello"
WARNING: Found orphan containers (po_mongodb_1, po_postgres_exporter_1, po_nginx_exporter_1, po_apache_exporter_1, po_mongodb_exporter_1, po_geoipupdate_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating po_backend_run ... done
hello

real	1m2.687s
user	0m1.097s
sys	0m0.195s
```
It's still 1 minute to mount :-(

So this does not seems to resolve the problem (still docker run alone is still fast, even if the same image as the one used for backend…).
